interface Watch{
    id:number;
        price:number;
        discount:number;
        modelNumber:string;
        trending:boolean;
        brand:string;
        collectionName:string;
        brandCountry:string;
        manufactureOrExported:string;
        importedBy:string;
        description:string;
        watchGlassOrCrystal:string;
        warranty:number;
        waterResistance:string;
        caseMaterial:string;
        gender:string;
        caseShape:string;
        dialColor:string;
        dialType:string;
        caseSizeMM = caseSizeMM;
        caseThicknessMM = caseThicknessMM;
        strapColor = strapColor;
        strapMaterial = strapMaterial;
        strapWidthMM = strapWidthMM;
        strapType = strapType;
        careInstruction = careInstruction;
